cookie:
  secret: 'REPLACE SECRET IN LOCAL.YAML'
ads:
  basePath: ""
  uploadPath: "upload"
  # stakeholderCase:
  #   contents:
  #     NodeList:
  #       - ThisNodeId: 1
  #         NodeType: 'Goal'
  #         Description:  "Stakeholders are identified in this project"
  #         Children: [2]
  #         Contexts: []
  #         MetaData: []
  #       - ThisNodeId: 2
  #         NodeType: 'Strategy'
  #         Description: 'Arguing over types of stakeholders'
  #         Children: [3]
  #         Contexts: []
  #         MetaData: []
  #       - ThisNodeId: 3
  #         NodeType: 'Goal'
  #         Description: 'Founders are identified'
  #         Children: [4]
  #         Contexts: []
  #         MetaData: []
  #       - ThisNodeId: 4
  #         NodeType: 'Evidence'
  #         Description: '%USER%'
  #         Children: []
  #         Contexts: []
  #         MetaData: []
  #     TopGoalId: 1
  #     NodeCount: 4
  #     DCaseName: 'Stakeholders'
redmine:
  host: "localhost"
  port: 80
  basePath: "/"
  apiKey: "GET API KEY FROM REDMINE"
  projectId: 1
mysql:
  host: 'localhost'
  user: 'root'
  password: ''
  database: 'ads'
rec:
  host: "localhost"
  port: 3030
  basePath: "/"
  monitorUrl: "http://live.assure-it.org/rec/api/1.0/evidenceList?nodeID=$1"
  api: "/rec/api/1.0"
ldap:
# When you make it operate by dummy OpenLDAP, please generate URL using dummyip and dummyport. 
#  url: 'ldap://localhost/cn=root,dc=assureit,dc=org'
  url: 'ldap://localhost:3040/cn=root,dc=assureit,dc=org'
  dn: 'uid=$1,ou=user,dc=assureit,dc=org'
  root: 'cn=root,dc=assureit,dc=org'
  password: 'ROOTPASSWORD'
  dummy:
    ip: 'localhost'
    port: 3040
passport:
  resolveURL: ''
  FACEBOOK_APP_ID: ''
  FACEBOOK_APP_SECRET: ''
  TWITTER_CONSUMER_KEY: ''
  TWITTER_CONSUMER_SECRET: ''
translator:
  CLIENT_ID: ''
  CLIENT_SECRET: ''
