ads:
  basePath: ""
redmine:
  host: "localhost"
  port: 80
  basePath: "/"
  apiKey: "GET API KEY FROM REDMINE"
  projectId: 1
mysql:
  host: 'localhost'
  user: 'ads_test'
  password: 'ads_test'
  database: 'ads'
rec:
  host: "localhost"
  port: 3030
  basePath: "/"
ldap:
# When you make it operate by dummy OpenLDAP, please generate URL using dummyip and dummyport. 
#  url: 'ldap://localhost/cn=root,dc=assureit,dc=org'
  url: 'ldap://localhost:3040/cn=root,dc=assureit,dc=org'
  dn: 'uid=$1,ou=user,dc=assureit,dc=org'
  root: 'cn=root,dc=assureit,dc=org'
  password: 'ROOTPASSWORD'
  dummyip: 'localhost'
  dummyport: 3040
